Do all validation steps before responding
Kataiser/CelesteTAS-Improvements-Tracker pull request #2
Opened 2024-02-17 13:03 UTC by jakobhellermann

So that when you have multiple errors, you don't have to repeatedly change something and repost.

![image](https://github.com/Kataiser/CelesteTAS-Improvements-Tracker/assets/22177966/1cb31457-2030-4c30-8914-5ac656aede63)

2024-02-17 18:39 UTC, Kataiser requested changes

2024-02-17 18:39 UTC, Kataiser commented on main.py
> +            warnings="\n".join(validation_result.warning_text)
This should be moved a line up (whitespace after, not before)

2024-02-17 18:39 UTC, Kataiser commented on validation.py
> +    log_text: List[str]
You can just do list[str] now fyi

2024-02-17 18:39 UTC, Kataiser commented on validation.py
> +    def emit_error(self, warning: str, log_message: str):
I don't really like this name, can't think of anything better but it's not really an error

2024-02-17 18:39 UTC, Kataiser commented on tests.py
I'll add a test for multiple validation failures

2024-02-18 04:09 UTC, Kataiser commented
Oh also can you make multiple failures in a response be in a markdown list please

2024-02-18 10:51 UTC, jakobhellermann commented on validation.py
> +    def emit_error(self, warning: str, log_message: str):
`emit_failed_check`?

2024-02-18 10:53 UTC, jakobhellermann commented on main.py
> +            warnings = validation_result.warning_text[0] if len(validation_result.warning_text) == 1 else format_markdown_list(validation_result.warning_text)
is there a preferred way to break these long lines like
```py
warnings = validation_result.warning_text[0]
    if len(validation_result.warning_text) == 1
    else format_markdown_list(validation_result.warning_text)
```
or
```py
warnings = validation_result.warning_text[0] if len(validation_result.warning_text) == 1 else(
    format_markdown_list(validation_result.warning_text)
)
```

alternatively the `format_markdown_list` function could do the single-element check and this line would be `warnings = format_markdown_list(validation_result.warning_text)`.

2024-02-18 10:54 UTC, jakobhellermann commented
![image](https://github.com/Kataiser/CelesteTAS-Improvements-Tracker/assets/22177966/e2a46571-1b30-47c1-a21d-35bf77dcb510)

2024-02-18 16:43 UTC, Kataiser commented on validation.py
> +    def emit_error(self, warning: str, log_message: str):
Sure

2024-02-18 16:44 UTC, Kataiser commented on main.py
> +            warnings = validation_result.warning_text[0] if len(validation_result.warning_text) == 1 else format_markdown_list(validation_result.warning_text)
I would say just break this into a full if-else instead of a ternary

2024-02-18 17:48 UTC, jakobhellermann commented on main.py
> +            warnings = validation_result.warning_text[0] if len(validation_result.warning_text) == 1 else format_markdown_list(validation_result.warning_text)
Done

2024-02-18 22:07 UTC, merged