Write lobby filetimes to google sheet
Kataiser/CelesteTAS-Improvements-Tracker pull request #4
Opened 2024-02-17 14:03 UTC by jakobhellermann

also includes the changes from #2 so reviewing that first should make this diff a bit easier to read

![image](https://github.com/Kataiser/CelesteTAS-Improvements-Tracker/assets/22177966/ec6b7336-2915-40fc-8196-4e5b1d07516a)

![image](https://github.com/Kataiser/CelesteTAS-Improvements-Tracker/assets/22177966/c009a734-7518-4b3a-8557-8d6e1c3b3c7e)

2024-02-17 18:49 UTC, Kataiser commented
I'd rather sheet ID be given via a separate command, or prompted when registering a lobby project, rather than part of the already bloated register project command params

2024-02-17 18:59 UTC, Kataiser requested changes

2024-02-17 18:59 UTC, Kataiser commented on commands.py
> +    (spreadsheet_id, _, cell) = lobby_sheet_cell.partition('/')
These parenthesis are redundant

2024-02-17 18:59 UTC, Kataiser commented on commands.py
> +    except Exception as e:
Tiniest nitpick ever but I'd prefer the exception to be named `error`

2024-02-17 18:59 UTC, Kataiser commented on commands.py
> +               f"\nLobby Sheet: `{project['lobby_sheet_cell']}`" \
This should be a markdown link, and not shown if not a lobby project

2024-02-17 18:59 UTC, Kataiser commented on spreadsheet.py
> +def write_sheet(spreadsheet: str, cell_range: str, new_values: List[List[Union[int, str]]]):
`list[list[Union[int, str]]]`

2024-02-17 18:59 UTC, Kataiser commented on spreadsheet.py
> +re_column_row = re.compile(r"([A-Z]+)(\d+)$")
This should be at the bottom, by `re_ping`

2024-02-17 18:59 UTC, Kataiser commented on spreadsheet.py
> +service_account_email: str = creds.service_account_email
What is this for?

2024-02-18 12:18 UTC, jakobhellermann commented on spreadsheet.py
> +service_account_email: str = creds.service_account_email
It's used in the setup command in the error for when the bot cannot access the google sheet.

```
Bot can't write to to https://docs.google.com/spreadsheets/d/1xY9W_fvKyYYz7E-t_t5UXSpqxECUil2mLY7PdB-ifLc at C2.
Make sure to invite bot-677@celestetasimprovementstracker.iam.gserviceaccount.com to the sheet.
```

2024-02-18 12:22 UTC, jakobhellermann commented
I moved the setup from the `register_project` command into a separate `link_lobby_sheet` command that can be used like this:
- `link_lobby_sheet Testing https://docs.google.com/spreadsheets/d/1xY9W_fvKyYYz7E-t_t5UXSpqxECUil2mLY7PdB-ifLc C3`
- `link_lobby_sheet Testing https://docs.google.com/spreadsheets/d/1xY9W_fvKyYYz7E-t_t5UXSpqxECUil2mLY7PdB-ifLc/edit#gid=0 "Beginner Lobby!C3"`
- `link_lobby_sheet Testing 1xY9W_fvKyYYz7E-t_t5UXSpqxECUil2mLY7PdB-ifLc A0`

Do you have any preferences for how you would unlink the sheet? `unlink_lobby_sheet testing`? `link_lobby_sheet Testing none`?

2024-02-18 16:46 UTC, Kataiser commented on spreadsheet.py
> +service_account_email: str = creds.service_account_email
Oh ok, I couldn't find the reference to it for some reason

2024-02-18 16:53 UTC, Kataiser commented
I don't need sheet unlinking support, people can just ask me if they need that

2024-02-18 17:12 UTC, Kataiser requested changes

2024-02-18 17:12 UTC, Kataiser commented on commands.py
> +    if len(projects) == 0:
Can just do `if not projects`

2024-02-18 17:12 UTC, Kataiser commented on commands.py
> +@command(re.compile(r'(?i)link_lobby_sheet .+ .+ (.+!)?[A-Z]+\d+'))
This should be a reported command, add `report_usage=True`

2024-02-18 17:12 UTC, Kataiser commented on commands.py
There are a bunch of formatting conflicts vs what I do, but I'll just fix them myself

2024-02-18 22:10 UTC, merged